# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: automationapi
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module automationapi.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/automationapi.db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./automationapi:/code/automationapi
      - ./db/:/db/
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: automationapi
    command: "celery worker -A automationapi.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
